"""add contracts and signatures

Revision ID: 512c1c8607d1
Revises: 0753bee6f9f4
Create Date: 2026-01-05 18:41:48.222667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512c1c8607d1'
down_revision = '0753bee6f9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('template_type', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_status'), ['status'], unique=False)

    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'user_id', name='uq_signature_contract_user')
    )
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signatures_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signatures_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signatures_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signatures_user_id'))
        batch_op.drop_index(batch_op.f('ix_signatures_status'))
        batch_op.drop_index(batch_op.f('ix_signatures_contract_id'))

    op.drop_table('signatures')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_contracts_created_by_id'))

    op.drop_table('contracts')
    # ### end Alembic commands ###
